---

- include_tasks: Redhat-docker.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian-docker.yml
  when: ansible_os_family == 'Debian'


- name: Docker service
  service:
          name: docker
          state: started
          enabled: yes

- name: run http container
  docker_container:
          name: web_container
          image: dsbios/omo-devops-test-task
          detach: no
          tty: yes
          interactive: yes
          published_ports:
                  - 4996:4996