- name: add docker gpg key
  rpm_key:
          key: https://download.docker.com/linux/centos/gpg
          state: present
  become: yes

- name: Docker Yum Setup
  yum_repository:
          name: docker-repo
          baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
          description: Docker yum repo setup
          gpgcheck: yes

- name: Python 3 install
  package:
          name: python38
          state: present

- name: Docker Module for Python
  pip:
          name: docker-py

- name: Install containerd.io
  package:
          name:  containerd.io.x86_64
          state: present

- name: Install docker
  package:
          name:  docker-ce-20.10.7
          state: present